# Generated by Django 4.1 on 2024-08-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0006_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicado",
            field=models.BooleanField(default=True),
        ),
    ]
